---
title: "Movie Recommendation System"
author: "Rodrigo Serrano"
date: "April, 2019"
output: html_document
---

```{r init}
library(jsonlite)
library(rvest)
library(purrr)
library(tidyverse)
library(magrittr)
library(tm)
library(topicmodels)
library(tidytext)
library(factoextra)
library(FactoMineR)
library(wesanderson)
library(GGally)

movies_db <- read_csv("tmdb-5000-movie-dataset/tmdb_5000_movies.csv")

credits_db <- read_csv("tmdb-5000-movie-dataset/tmdb_5000_credits.csv")

genres <- movies_db %>%
        filter(nchar(genres) > 2) %>%
        mutate(aux_json = lapply(genres, fromJSON)) %>%
        unnest(aux_json) %>%
        select(id, genres = name) %>%
        mutate_if(is.character, factor)

prod_comp <- movies_db %>%
        filter(nchar(production_companies) > 2) %>%
        mutate(aux_json = lapply(production_companies, fromJSON)) %>%
        unnest(aux_json) %>%
        select(id, production_companies = name) %>%
        mutate_if(is.character, factor)

cast <- credits_db %>% 
  filter(nchar(cast) > 2) %>% 
  mutate(aux_json = lapply(cast, fromJSON)) %>% 
  unnest(aux_json) %>% 
  filter(order < 5) %>% 
  select(movie_id, name)
  
director <- credits_db %>% 
  filter(nchar(crew) > 2) %>% 
  mutate(aux_json = lapply(crew, fromJSON)) %>% 
  unnest(aux_json) %>% 
  filter(department == 'Directing' & job == 'Director') %>% 
  select(movie_id, name)

```

```{r top_directors}

genre_1 <- genres %>% group_by(id) %>% summarise(genre = first(genres))

top_directors <- director %>% 
  count(name) %>% 
  top_n(20, wt = n) %>%  
  select(name) %>% 
  pull()

director %>% 
  filter(name %in% top_directors) %>% 
  left_join(genre_1, by = c('movie_id' = 'id')) %>% 
  count(name, genre) %>% 
  ggplot(aes(x = name, y = n, fill = genre)) +
  geom_col() + 
  coord_flip() +
  scale_fill_manual(values = wes_palette('Darjeeling1', length(unique(genre_1$genre)), type = 'continuous'))
```

```{r top_actors}
top_actors <- cast %>% 
  count(name) %>% 
  top_n(20, wt = n) %>%  
  select(name) %>% 
  pull()

cast %>% 
  filter(name %in% top_actors) %>% 
  left_join(genre_1, by = c('movie_id' = 'id')) %>% 
  count(name, genre) %>% 
  ggplot(aes(x = name, y = n, fill = genre)) +
  geom_col() + 
  coord_flip() +
  scale_fill_manual(values = wes_palette('Darjeeling1', length(unique(genre_1$genre)), type = 'continuous'))
```

```{r ggpair}

lowerFn <- function(data, mapping, method = "lm") {
  ggplot(data = data, mapping = mapping) +
    geom_point(colour = "slategray4", size = 2, shape = 18) +
    geom_smooth(method = method, color = "coral3") +
    theme_minimal()
}

movies_db %>% 
  select(budget, revenue, release_date, vote_average, vote_count, runtime) %>%
  na.omit() %>% 
  ggpairs(lower = list(continuous = wrap(lowerFn, method = "lm")),
    diag = list(continuous = wrap("barDiag", fill = 'skyblue1', colour = "skyblue4")),
    upper = list(continuous = wrap("cor", size = 5)),
    progress = FALSE)

```

```{r votes}

movies_db %>%
  select(vote_average, vote_count) %>% 
  summary()

movies_db %>% 
  filter(vote_count > 235) %>%
  select(id, title, vote_average) %>%
  left_join(genre_1, by = 'id') %>%
  top_n(20, wt = vote_average) %>% 
  ggplot(aes(x = reorder(title, vote_average), y = vote_average, fill = genre)) +
  geom_col() + 
  coord_flip() +
  scale_fill_manual(values = wes_palette('Rushmore', 6, type = 'continuous'))
  

```

```{r colaborations}

director %>% 
  left_join(cast, by = 'movie_id') %>%
  left_join(movies_db %>% select(id, revenue), by = c('movie_id' = 'id')) %>% 
  transmute(director = name.x, actor = name.y, revenue,
            colaboration = paste(director, actor, sep = '-')) %>% 
  filter(director != actor) %>% 
  group_by(colaboration) %>% 
  summarise(n = n(), revenue = sum(revenue)) %>% 
  top_n(15, wt = n) %>% 
  ggplot(aes(x = reorder(colaboration, revenue), y = n)) +
  geom_col(fill = wes_palette('Royal1', 1, type = 'discrete')) + 
  coord_flip() +
  geom_text(aes(label = paste(round(revenue/1000000,1), 'M')), y = 0.5, size = 3, 
            colour = wes_palette('Darjeeling2', 1, type = 'discrete'))
  
```

```{r system_metadata}

pasted_genres <- genres %>% 
  mutate(genres = str_replace_all(genres, ' ', '')) %>% 
  group_by(id) %>% 
  summarise(genres = paste(genres, collapse = ' ' ))

pasted_directors <- director %>% 
  mutate(director = str_replace_all(name, ' ', '')) %>% 
  group_by(movie_id) %>% 
  summarise(director = first(director))

pasted_cast <- cast %>%
  mutate(actors = str_replace_all(name, ' ', '')) %>% 
  group_by(movie_id) %>% 
  summarise(actors = paste(actors, collapse = ' ' ))

corpus_metadata <- movies_db %>%
  select(id, title) %>% 
  distinct(title, .keep_all = TRUE) %>% 
  left_join(pasted_genres, by = 'id') %>% 
  left_join(pasted_directors, by = c('id' = 'movie_id')) %>% 
  left_join(pasted_cast, by = c('id' = 'movie_id')) %>% 
  transmute(doc_id = title, text = paste(genres, director, actors)) %>% 
  as.data.frame() %>% 
  DataframeSource() %>%
  Corpus()

docterm_metadata <- DocumentTermMatrix(corpus_metadata,
                        control = list(weighting = function(x) weightBin(x)))

frec_matrix <- docterm_metadata %>% as.matrix()

recommender <- function(matr, title = 'Avatar', db = movies_db){
  ind <- which(row.names(matr) == title)
  
  frec_movie <- matr[ind,]
  
  mutual_terms <- sweep(matr, 2, frec_movie, '+')

  most_frec <- apply(mutual_terms, 1, function(x) {sum(x == 2)})

  recomms <- data.frame(title = names(most_frec), frec = most_frec) %>% 
    mutate_if(is.character, factor) %>% 
    left_join(db %>%
                select(title, vote_average) %>% 
                distinct(title, .keep_all = TRUE) %>% 
                mutate_if(is.character, factor), 
              by = 'title') %>% 
    arrange(desc(frec), desc(vote_average)) %>% 
    select(title) %>% 
    head(10)
  
  return(recomms)
}

recommender(frec_matrix, 'Memento')


```

